include: package:flutter_lints/flutter.yaml

linter:
  # A list of all available lints and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    sort_child_properties_last: false
    use_key_in_widget_constructors: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
